import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@repo/web-ui/styles.css'
import './globals.css'
import { ThemeProvider } from '@/provider/theme-provider'
import { ViewportProvider } from '@/provider/viewport-provider'
import { QueryProvider } from '@/provider/query-provider'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from '@repo/web-ui/components'
import { KeystrokesProvider } from '@/provider/keystroke-provider'

const inter = Inter({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={inter.className}>
          <QueryProvider>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
              <ViewportProvider>
                <KeystrokesProvider>
                  {children}
                  <Toaster />
                </KeystrokesProvider>
              </ViewportProvider>
            </ThemeProvider>
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
